language: python
python:
  - "2.7"

install: sh install.sh

script: 
  - cd tests
  - ./test_cg.sh
  - ./test_anm.sh
  - ./test_common_residues.sh
  - ./test_msf.sh
  - ./test_get_aligned.sh
  - ./test_conformation.sh
