language: python

branches:
    only:
        - master

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: osx
      lanuage: generic
  allow_failures:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt install python-tk     ; fi

install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install numpy
  - pip install matplotlib
  - pip install cython
  - pip install mdtraj

script: 
  - cd tests
  - ./test_cg.sh
  - ./test_anm.sh
  - ./test_eigen_vectors.sh
  - ./test_common_residues.sh
  - ./test_msf.sh
  - ./test_get_aligned.sh
  - ./test_conformation.sh
  - ./test_trajectory.sh
