language: python

branches:
    only:
        - master

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: osx
      lanuage: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python2     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "oxs" ]]; then 

install: sh install.sh

script: 
  - cd tests
  - ./test_cg.sh
  - ./test_anm.sh
  - ./test_eigen_vectors.sh
  - ./test_common_residues.sh
  - ./test_msf.sh
  - ./test_get_aligned.sh
  - ./test_conformation.sh
  - ./test_trajectory.sh
