language: python
python:
  - "2.7"

os:
  - linux
  - osx
  
dist:
  - trusty
  
matrix:
  allow_failures:
    - os: osx
  
install: sh install.sh

script: 
  - cd tests
  - ./test_cg.sh
  - ./test_anm.sh
  - ./test_eigen_vectors.sh
  - ./test_common_residues.sh
  - ./test_msf.sh
  - ./test_get_aligned.sh
  - ./test_conformation.sh
  - ./test_trajectory.sh
