language: python

branches:
    only:
        - master

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: osx
      lanuage: generic
  allow_failures:
    - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python2     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tar     ; fi
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script: 
  - cd tests
  - ./test_cg.sh
  - ./test_anm.sh
  - ./test_eigen_vectors.sh
  - ./test_common_residues.sh
  - ./test_msf.sh
  - ./test_get_aligned.sh
  - ./test_conformation.sh
  - ./test_trajectory.sh
