branches:
    only:
        - master

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      sudo: required
      apt:
       packages:
        - python-tk
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python-tk; fi

install:
  - pip install --upgrade pip
  - pip install numpy
  - pip install matplotlib
  - pip install cython
  - pip install mdtraj

script: 
  - cd tests
  - ./test_cg.sh
  - ./test_anm.sh
  - ./test_eigen_vectors.sh
  - ./test_common_residues.sh
  - ./test_msf.sh
  - ./test_get_aligned.sh
  - ./test_conformation.sh
  - ./test_trajectory.sh
